### ISSUE TITLE
Add meta tags

### ISSUE THREAD

**Issue by SakshiShreya** [SakshiShreya/first-step-pharma-fe#5]
PR should have at least these meta tags:

- [x] Favicon
- [ ] Title and description
- [x] OG tags (For FB, LinkedIn and other social media)
- [x] Twitter tags
- [ ] Theme colour tag

## Suggestions

- Any other meta tags which are required are also welcome.
- You can refer **gantt-proj** for meta tags. Go to `src/index.html`.

**Comment by SakshiShreya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Initial setup](https://trello.com/c/WaLnDxIg/6-initial-setup)

**Comment by SakshiShreya** [comment]
@krishna1212031 I have added one more checkbox in description.
